workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    environment:
      groups:
        - keystore_credentials
      vars:
        PACKAGE_NAME: "com.evoworks.app"
      node: 18.17.0
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web app
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync android
      - name: Build Android
        script: |
          cd android
          ./gradlew bundleRelease
    artifacts:
      - android/app/build/outputs/**/*.aab
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal

